# Generated by Django 4.2.5 on 2023-10-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id_accidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_accidente', models.TextField()),
                ('estado_accidente', models.TextField()),
            ],
            options={
                'db_table': 'accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut_administrador', models.TextField(primary_key=True, serialize=False)),
                ('primer_nombre', models.TextField()),
                ('segundo_nombre', models.TextField()),
                ('apellido_p', models.TextField()),
                ('apellido_m', models.TextField()),
                ('telefono_administrador', models.TextField()),
                ('direccion_administrador', models.TextField()),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id_afp', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'afp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id_checklist', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.TextField()),
                ('observaciones', models.TextField()),
                ('extras', models.TextField()),
            ],
            options={
                'db_table': 'checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.TextField(primary_key=True, serialize=False)),
                ('razon_social', models.TextField()),
                ('telefono', models.TextField()),
                ('moroso', models.CharField(max_length=1)),
                ('direccion', models.TextField()),
                ('inicio_actividades', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('patente_municipal', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.TextField()),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_contrato', models.TextField()),
                ('fecha_inicio', models.TextField()),
                ('dia_pago', models.TextField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoProfesional',
            fields=[
                ('id_contrato_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.TextField()),
                ('hora_extra', models.TextField()),
                ('sueldo_liquido', models.BigIntegerField()),
                ('sueldo_bruto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'contrato_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.TextField()),
                ('monto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.TextField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo_prevision', models.TextField()),
            ],
            options={
                'db_table': 'prevision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('rut_profesional', models.TextField(primary_key=True, serialize=False)),
                ('primer_nombre', models.TextField()),
                ('segundo_nombre', models.TextField()),
                ('apellido_p', models.TextField()),
                ('apellido_m', models.TextField()),
                ('telefono_profesional', models.TextField()),
                ('direccion_profesional', models.TextField()),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.TextField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubroCliente',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'rubro_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id_tipo_accidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_tipo_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.TextField()),
                ('contrasena', models.TextField()),
                ('habilitado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id_validacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_validacion', models.TextField()),
            ],
            options={
                'db_table': 'validacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialServicio',
            fields=[
                ('cantidad', models.BigIntegerField()),
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.servicio')),
            ],
            options={
                'db_table': 'material_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioPlan',
            fields=[
                ('cantidad', models.BigIntegerField()),
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.servicio')),
            ],
            options={
                'db_table': 'servicio_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidacionChecklist',
            fields=[
                ('cumplido', models.CharField(max_length=1)),
                ('id_validacion', models.OneToOneField(db_column='id_validacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.validacion')),
            ],
            options={
                'db_table': 'validacion_checklist',
                'managed': False,
            },
        ),
    ]
